// Logic label values, per control, keyed by the locale identifier Logic reports.
//
// GENERATED by Scripts/locale_labels.py --write from AXLocalePolicy.swift and
// docs/canon/index/. Do not edit: the next --write overwrites it, and the policy is where
// a label is added, cited and checked.
//
// A LabelSet answers "does this reading match?" and that is the right question almost
// everywhere. It cannot answer "which spelling do I TYPE on this host?", because its
// members carry no locale. These tables answer that one, and they are derived rather than
// written: each value is the member whose case-folded digest equals the digest Apple's own
// row is pinned to in that locale.
enum AXLocaleValues {

    /// ArmKeyCommandSetup.searchQuery types this into the Key Commands filter, and the filter is a
    /// live search -- the wrong language collapses the list to nothing and the setup then reports
    /// `could not find the command` having never had a chance.
    /// Apple's row: logic-canon://strings/Contents%2FFrameworks%2FLogic.framework%2FVersions%2FA%2FResources%2FLocalizable.strings/en/Toggle%20Track%20Record%20Enable#value
    static let recordArmKeyCommandName: [String: String] = [
        "en-US": "Toggle Track Record Enable",
        "ko-KR": "트랙 녹음 활성화 토글",
        "ja-JP": "トラックの録音可能を切り替え",
        "de-DE": "Spur für die Aufnahme aktivieren ein-/aus",
        "es-ES": "Activar/desactivar grabación de pista",
        "fr-FR": "Activer/Désactiver l’enregistrement sur piste",
        "it-IT": "Attiva/disattiva abilitazione registrazione traccia",
        "pt-BR": "Ativar/Desativar Gravação das Pistas",
        "zh-CN": "开关轨道录音启用",
        "zh-TW": "切換音軌錄音啟用",
        "de": "Spur für die Aufnahme aktivieren ein-/aus",
        "en": "Toggle Track Record Enable",
        "es": "Activar/desactivar grabación de pista",
        "fr": "Activer/Désactiver l’enregistrement sur piste",
        "it": "Attiva/disattiva abilitazione registrazione traccia",
        "ja": "トラックの録音可能を切り替え",
        "ko": "트랙 녹음 활성화 토글",
        "pt": "Ativar/Desativar Gravação das Pistas",
    ]
}
